apiVersion: v1
kind: Secret
metadata:
  name: devops-secret
  annotations:
    pingctl.user: samirgandhi@pingidentity.com
    pingctl.app-version: v1.0.3
type: Opaque
data:
  PING_IDENTITY_DEVOPS_USER: "${PING_IDENTITY_DEVOPS_USER_BASE64}"
  PING_IDENTITY_DEVOPS_KEY: "${PING_IDENTITY_DEVOPS_KEY_BASE64}"
  PING_IDENTITY_ACCEPT_EULA: WUVT